# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    filePath: 'https://raw.githubusercontent.com/BonsaiAI/solution-accelerator-tests/main/logistics_supply_chain/factory_logistics/scripts/deployment_test.ps1?token=ADFTVNM7ETYOPDCD2NAGRMLAKNY26'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'
    outputFormat: 'sarif'